---
title: "Práctica 5 mar-ago23"
author: "JCLL"
format: docx
editor: visual
---

# **Distribuciones discretas**

# 

## Ejercicio 1

```{r}
# Ejericio 1 
# Calcular la probabilidad que la quinta persona expuesta a esta enfermedad sea la segunda en contraerla.

(personas = dnbinom(x= 3,size=2,prob = 0.3)) # x representa la cantidad de fracasos que se tiene en el experimento, size = representa cantidad de éxitos
```

```{r}
# Segundo ejercicios
# k = 1 
# p = 2/10

dgeom(5,2/10) # x es el valor que pide el R, es la cantidad de fallos antes de encontrar el primer éxito

dgeom(x=0:6, 2/10)
(sum(dgeom(x=0:6,2/10)))
pgeom(6,2/10)
qgeom(0.4, 2/10)

# grafica de la distribución geometrica
plot (x=0:6, y = dgeom(x=0:6,2/10),
      type= "h") # grafica 

```

```{r}
# Literal b
# Distribuición negativa 
# porque k > 1

dnbinom(1,2, 0.5)

# El quinto hijo sea el tecer varón 
dnbinom(2,3, 0.5)
# El quinto hijo sea la cuarta mujer 
dnbinom(1,4, 0.5)

(prob1 = dnbinom(2,3, 0.5) + dnbinom(1,4, 0.5))
```

```{r}
# Distribución hypergeométrica

m <- 6; n <- 4; k <- 3 # m es el número de éxitos, n es el número de fracasos, y k es la muestra aleatoria
x <- 0:(k)
dhyper(x, m, n, k)
# probabilidad no más de una defectuosa
phyper(1, m, n, k)
# al menos una defectuosa 

(g= 1 - phyper(0, m, n, k))



```

#Determinar qué tipo de distribución se aplica en el ejercicio 50 y 68

# Distribución Poisson

```{r}
# P (X=8)

dpois(8,5)

# P(X<= 8)
ppois(8,5)

x=0:8
sum(dpois(x,5))

# P(9<= X)
# P(9<= X) = 1 - P(X < 9)
(P9 = 1- ppois(8,5))

# P(5<= X <= 8)
dpois(x=c(5,8),5)

ppois(5,5); ppois(8,5) 
(f= ppois(8,5)-ppois(5,5))
# P(5 < X < 8)
x= c(6,7)
p=ppois(x,5)

p[2]-p[1]

# Prueba de lamda
ppois(4,5)
ppois(4,3.75) 

x= 0: 100
ppois(x,3.75)
```

```{r}
# Distribución continua, Normal Estándar

dnorm(1.45,mean=0,sd=1)

pnorm(1.49, mean=0,sd=1, lower.tail=T)

```
